/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "TransparentWnd.h"
#include "DeskWndObserver.h"
#include <string>

juce_ImplementSingleton(DeskWndObserver)

//==============================================================================
class NewProjectApplication  
    : public JUCEApplication
{
public:
    //==============================================================================
    NewProjectApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        LoadDtdData::getInstance()->parseDtdFile("strings.dtd");
        BookmarkFileIO::getInstance()->init("bookmarks.json");

        DeskWndObserver::getInstance()->FindTargetWnd();
        DeskWndObserver::getInstance()->FindAccObj();
        
        RECT rct = DeskWndObserver::getInstance()->getFavirateRect();
        juce::Rectangle<int> wndPos(int(rct.left * 0.8f), int(rct.top * 0.8f), 
            int(rct.right * 0.8f), int(rct.bottom * 0.8f));
        wnd = new TransparentWnd(wndPos);
        wnd->addToDesktop(ComponentPeer::windowIsTemporary);
        wnd->setAlwaysOnTop(true);
        wnd->setVisible(true);
        // Add your application's initialisation code here..
    }

    void shutdown()
    {
        BookmarkFileIO::getInstance()->saveToFile();
        BookmarkFileIO::deleteInstance();
        LoadDtdData::deleteInstance();
        DeskWndObserver::deleteInstance();
        wnd = nullptr;
        // Add your application's shutdown code here..
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

private:
    ScopedPointer<TransparentWnd> wnd;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (NewProjectApplication)
